# Generated by Django 3.2 on 2022-03-14 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinkr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_dob',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
