# Generated by Django 3.2 on 2022-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkr', '0003_alter_userdata_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_dislikes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_drinks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_favs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_modifers',
            field=models.TextField(null=True),
        ),
    ]
