# Generated by Django 3.2 on 2022-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drinkr", "0004_auto_20220314_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="new_ingredients",
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
